Repository WildCodeSchool/2022-09-php-orleans-project-ecurieorleans, pull requests merged in 2022-11, with the labels that each got.

#117 fixed height of header and deleted arrows media querry
  public/assets/css/home.css
  public/assets/css/root.css
  src/View/Home/index.html.twig
Labels: Reviewed

#115 fixed the titles sizes, colors and borders of homepage
  public/assets/css/home.css
  public/assets/css/presentation.css
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed, Corrections done

#113 S02 us31 footer
  database.sql
  public/assets/css/footer.css
  public/assets/images/FFM-logo.png
  public/assets/images/FFSA-logo.jpg
  public/assets/images/RCVL-logo.png
  public/assets/images/ufolep-logo.png
  src/Controller/AbstractController.php
  src/Model/PartnerManager.php
  src/View/Components/_footer.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Corrections done

#140 S02 us125 header section sport
  database.sql
  public/assets/css/navbar.css
  public/assets/css/section.css
  public/assets/images/imgPlaceHolder.webp
  public/assets/upload/.gitignore
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/Controller/SectionController.php
  src/Model/SectionManager.php
  src/View/Components/_navbar.html.twig
  src/View/Section/section.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#143 correction on the responsiveness of the footer
  public/assets/css/footer.css
  src/View/Components/_footer.html.twig
Labels: Reviewed

#142 S02US03 fix responsive card + design card
  database.sql
  public/assets/css/card.css
  public/assets/css/home.css
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed, Corrections done

#146 Dev->main #3
  database.sql
  public/assets/css/card.css
  public/assets/css/circuit.css
  public/assets/css/footer.css
  public/assets/css/home.css
  public/assets/css/navbar.css
  public/assets/css/presentation.css
  public/assets/css/root.css
  public/assets/css/section.css
  public/assets/css/style.css
  public/assets/images/FFM-logo.png
  public/assets/images/FFSA-logo.jpg
  public/assets/images/RCVL-logo.png
  public/assets/images/circuit.webp
  public/assets/images/circuit_description.webp
  public/assets/images/circuit_presentation.jpeg
  public/assets/images/imgPlaceHolder.webp
  public/assets/images/logo.png
  public/assets/images/ufolep-logo.png
  public/assets/upload/.gitignore
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/Controller/SectionController.php
  src/Model/PartnerManager.php
  src/Model/SectionManager.php
  src/View/Circuit/circuit.html.twig
  src/View/Components/_footer.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/Section/section.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed, Dev -> Main

#147 fixed indentation of main on homepage
  src/View/Home/index.html.twig
Labels: Reviewed

#149 fix database
  database.sql
Labels: Reviewed

#145 S02 us27 home gallery
  public/assets/css/home.css
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, Corrections done

#153 dev->Main n°4
  database.sql
  public/assets/css/home.css
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, Dev -> Main

#155 change card design
  src/View/Home/index.html.twig
Labels: Reviewed

#158 fixed card
  src/View/Home/index.html.twig
Labels: Reviewed

#144 S02 us29 bureau page
  database.sql
  public/assets/css/bureau.css
  public/assets/css/style.css
  public/assets/images/bureau_members.png
  public/assets/images/conseil_admistration.png
  src/Controller/BoardController.php
  src/Controller/HomeController.php
  src/Model/BoardManager.php
  src/View/Bureau/bureau.html.twig
  src/View/Components/_navbar.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#154 show eventCard in admin part
  src/Controller/EventAdminController.php
  src/View/AdminEvent/AdminEvent.html.twig
  src/routes.php
Labels: Reviewed

#148 S02US05 ajout de la partie nous rejoindre
  public/assets/css/home.css
  public/assets/images/BMW.jpg
  src/View/Home/index.html.twig
Labels: Reviewed, Conflicts resolve

#160 added home link to logo navbar
  src/View/Components/_navbar.html.twig
Labels: Reviewed

#162 corrected home arrows
  public/assets/css/home.css
Labels: Reviewed

#163 fix join part
  src/View/Home/index.html.twig
Labels: Reviewed, Corrections done

#164 fixed spacers in navbar
  public/assets/css/navbar.css
Labels: Reviewed, To be reviewed

#156 form
  database.sql
  public/assets/css/form.css
  public/assets/css/root.css
  src/Controller/FormController.php
  src/Model/FormManager.php
  src/View/Contact/form.html.twig
  src/View/Item/_form.html.twig
  src/routes.php
Labels: Reviewed, Conflicts resolve

#168 fix route contact
  src/View/Components/_footer.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#167 change spacing title join part
  src/View/Home/index.html.twig
Labels: Reviewed

#169 dev->main n°6
  database.sql
  public/assets/css/form.css
  public/assets/css/root.css
  src/Controller/FormController.php
  src/Model/FormManager.php
  src/View/Components/_footer.html.twig
  src/View/Contact/form.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_form.html.twig
  src/routes.php
Labels: Reviewed, Dev -> Main

#170 fix database
  database.sql
Labels: Reviewed

#171 dev->main
  database.sql
Labels: Reviewed, Dev -> Main

#152 made navbar admin and route to admin homepage
  public/assets/css/navbar_admin.css
  src/Controller/AdminController.php
  src/View/Administration/home_admin.html.twig
  src/View/Circuit/circuit.html.twig
  src/View/Components/_admin_navbar.html.twig
  src/View/Components/_footer.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/Section/section.html.twig
  src/View/admin_layout.html.twig
  src/View/layout.html.twig
  src/View/visitor_layout.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#178 S03 us78 circuit find us section
  public/assets/css/circuit.css
  src/View/Circuit/circuit.html.twig
Labels: Reviewed, Corrections done

#180 S03 us132 admin sport view
  public/assets/css/style.css
  src/Controller/AdminSectionController.php
  src/View/AdminSports/adminSports.html.twig
  src/View/Components/_addButton.html.twig
  src/View/Components/_deleteButton.html.twig
  src/View/Components/_editButton.html.twig
  src/View/Components/_navbar.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#182 fixed urls and bureau layout
  src/View/Bureau/bureau.html.twig
  src/View/Components/_navbar.html.twig
Labels: Reviewed

#183 modified database with constraints on sectionID
  database.sql
Labels: Reviewed

#185 S03 us176 sport sections edit layout
  public/assets/css/style.css
  src/Controller/AdminSectionController.php
  src/View/AdminSports/adminEditSports.twig
  src/View/AdminSports/adminSports.html.twig
  src/View/Components/_addButton.html.twig
  src/View/Components/_admin_form_edit_sports.html.twig
  src/View/Components/_admin_navbar.html.twig
  src/View/Components/_deleteButton.html.twig
  src/View/Components/_editButton.html.twig
  src/View/Components/_validateButton.html.twig
  src/routes.php
Labels: Reviewed

#188 S03US22 view eventadmin part
  src/View/AdminEvent/AdminEvent.html.twig
Labels: Reviewed

#190 fixed global links due to bad conflict resolve and made asso presenta…
  src/Controller/EventAdminController.php
  src/Controller/HomeController.php
  src/Model/AssociationManager.php
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#193 S03US13 vue admin + connexion
  database.sql
  src/Controller/AbstractController.php
  src/Controller/LoginController.php
  src/Model/LoginManager.php
  src/View/Components/_admin_navbar.html.twig
  src/View/Login/Login.html.twig
  src/routes.php
Labels: Reviewed

#207 S03 us20 crud edit sports
  public/assets/css/style.css
  public/assets/uploads/.gitignore
  src/Controller/AdminSectionController.php
  src/Model/SectionManager.php
  src/View/AdminSports/adminSports.html.twig
  src/View/Components/_admin_form_edit_sports.html.twig
  src/View/Components/_validateButton.html.twig
  src/View/Home/index.html.twig
  src/View/Section/section.html.twig
Labels: Reviewed

#208 S03 us130 crud add sections sports
  src/Controller/AdminSectionController.php
  src/Model/SectionManager.php
  src/View/AdminSports/adminAddSports.html.twig
  src/View/AdminSports/adminSports.html.twig
  src/View/Components/_admin_form_add_sports.html.twig
  src/routes.php
Labels: Reviewed, Conflicts resolve

#210 fix database
  database.sql
Labels: Reviewed

#213 S03US25 update event
  database.sql
  src/Controller/EventAdminController.php
  src/Model/EventManager.php
  src/View/AdminEvent/AddAdminEvent.html.twig
  src/View/AdminEvent/AdminEvent.html.twig
  src/View/AdminEvent/EditAdminEvent.html.twig
  src/View/Components/_admin_navbar.html.twig
  src/routes.php
Labels: Reviewed

#192 partners
  database.sql
  public/assets/css/partner.css
  public/assets/images/partner1.jpeg
  src/Controller/PartnerController.php
  src/View/Components/_footer.html.twig
  src/View/Partners/partner.html.twig
  src/routes.php
Labels: Reviewed

#216 deleted bind value id on insert
  src/Model/SectionManager.php
Labels: Reviewed

#215 S03US131-CRUD_delete-sections_sports
  database.sql
  src/Controller/AdminSectionController.php
  src/Model/SectionManager.php
  src/View/AdminSports/adminSports.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#214 S03US32 crud add partner
  database.sql
  src/Controller/AdminPartnerController.php
  src/Model/PartnerManager.php
  src/View/AdminPartner/AdminPartner.html.twig
  src/View/AdminPartner/addPartner.html.twig
  src/routes.php
Labels: Reviewed, Conflicts resolve

#219 fix_admin_add_sports_button
  src/View/AdminSports/adminSports.html.twig
Labels: Reviewed

#220 S03US126-Layout_sections_sports
  database.sql
  public/assets/css/card.css
  public/assets/css/section.css
  public/assets/css/style.css
  src/Controller/SectionController.php
  src/Model/BoardManager.php
  src/Model/EventManager.php
  src/View/Section/section.html.twig
  src/routes.php
Labels: Reviewed

#221 fixed route partenaire
  src/routes.php
Labels: Reviewed

#223 deleted logos from footer
  public/assets/images/logo-placeholder.png
  src/View/Components/_footer.html.twig
Labels: Reviewed, Conflicts resolve

#224 dev -> main
  database.sql
  public/assets/css/card.css
  public/assets/css/home.css
  public/assets/css/section.css
  public/assets/css/style.css
  public/assets/images/logo-placeholder.png
  src/Controller/AdminPartnerController.php
  src/Controller/SectionController.php
  src/Model/BoardManager.php
  src/Model/EventManager.php
  src/Model/PartnerManager.php
  src/View/AdminPartner/AdminPartner.html.twig
  src/View/AdminPartner/addPartner.html.twig
  src/View/AdminSports/adminSports.html.twig
  src/View/Components/_footer.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/Section/section.html.twig
  src/routes.php
Labels: Reviewed, Dev -> Main

#225 moved uploads file
  public/uploads/.gitignore
Labels: Reviewed

#241 S03 us35 show admin bureau
  src/Controller/AdminBoardController.php
  src/View/AdminBoard/AdminBoard.html.twig
  src/routes.php
Labels: Reviewed

#240 changed sections layout
  public/assets/css/section.css
  public/assets/css/style.css
  src/Controller/SectionController.php
  src/View/Section/section.html.twig
Labels: Reviewed

#239 changed bureau layout
  public/assets/css/bureau.css
  public/assets/images/bureau-cover.jpg
  src/View/Bureau/bureau.html.twig
Labels: Reviewed

#237 fixed-add-event
  src/View/AdminEvent/AddAdminEvent.html.twig
Labels: Reviewed

#233 Fix contact form
  public/assets/css/form.css
  src/Controller/FormController.php
  src/View/Contact/form.html.twig
Labels: Reviewed

#235 fixed edit event form
  src/View/AdminEvent/EditAdminEvent.html.twig
Labels: Reviewed

#234 fixed path to uploads
  src/Controller/AdminSectionController.php
  src/View/AdminEvent/AdminEvent.html.twig
  src/View/AdminPartner/AdminPartner.html.twig
  src/View/AdminSports/adminSports.html.twig
  src/View/Home/index.html.twig
  src/View/Partners/partner.html.twig
  src/View/Section/section.html.twig
Labels: Reviewed, Conflicts resolve

#243 S04US37 delete
  src/Controller/AdminBoardController.php
  src/View/AdminBoard/AdminBoard.html.twig
  src/routes.php
Labels: Reviewed

#242 S03US36 partie ajout d'un membre
  src/Controller/AdminBoardController.php
  src/Model/BoardManager.php
  src/View/AdminBoard/AdminAddBoard.html.twig
  src/View/Components/_admin_navbar.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#245 added content to the admin homepage
  public/assets/images/car.gif
  src/Controller/AdminController.php
  src/Model/AdminManager.php
  src/View/Administration/home_admin.html.twig
Labels: Reviewed

#246 S04US00 secure admin
  public/assets/images/error.webp
  src/Controller/AbstractController.php
  src/Controller/AdminBoardController.php
  src/Controller/AdminController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminSectionController.php
  src/Controller/ErrorController.php
  src/Controller/EventAdminController.php
  src/View/Error/Error.html.twig
  src/routes.php
Labels: Reviewed, Corrections done, Conflicts resolve

#247 2nd version of navbar
  public/assets/css/navbar.css
  public/assets/images/5457169.jpg
  src/View/Components/_navbar.html.twig
  src/routes.php
Labels: Reviewed

#249 fix route home
  src/View/Components/_navbar.html.twig
  src/routes.php
Labels: Reviewed

#244 S04US38 edit member
  src/Controller/AdminBoardController.php
  src/Model/BoardManager.php
  src/View/AdminBoard/AdminBoard.html.twig
  src/View/AdminBoard/AdminEditBoard.html.twig
  src/routes.php
Labels: Reviewed

#254 fix_edit_member
  src/Controller/AdminBoardController.php
Labels: Reviewed

#253 change image admin
  public/assets/images/error.jpeg
  public/assets/images/error.webp
  src/View/Error/Error.html.twig
Labels: Reviewed

#252 mentions legales
  src/Controller/MentionLegaleController.php
  src/View/Components/_footer.html.twig
  src/View/MentionsLegale/MentionsLegale.html.twig
  src/routes.php
Labels: Reviewed

#248 Fix homepage style
  public/assets/css/card.css
  public/assets/css/home.css
  public/assets/css/style.css
  public/assets/images/home-events-cover.jpg
  src/Controller/HomeController.php
  src/Model/EventManager.php
  src/View/Home/index.html.twig
Labels: Changes requested

#256 fix page partner
  public/assets/css/partner.css
  src/View/Partners/partner.html.twig
Labels: Reviewed

#257 fix margin image header
  src/View/Section/section.html.twig
Labels: Reviewed

#258 fix route button contact
  src/View/Home/index.html.twig
Labels: Reviewed

#259 delete css not use in partner.css
  public/assets/css/partner.css
Labels: Reviewed

#260 fix navbarcss
  public/assets/css/navbar.css
Labels: Reviewed

#262 fix width
  src/View/Bureau/bureau.html.twig
  src/View/Circuit/circuit.html.twig
Labels: Reviewed

#261 name logo=NULL in database for placeholder in partner
  database.sql
Labels: Reviewed

#267 changed style
  public/assets/css/circuit.css
  src/View/Circuit/circuit.html.twig
Labels: Reviewed

#268 Fix style bureau
  public/assets/css/bureau.css
  src/View/Bureau/bureau.html.twig
Labels: Reviewed

#263 fix button section
  src/Controller/FormController.php
  src/View/Components/_navbar.html.twig
Labels: Reviewed

#266 Fix style sections
  public/assets/css/card.css
  public/assets/css/navbar.css
  public/assets/css/section.css
  src/Controller/AdminBoardController.php
  src/Controller/HomeController.php
  src/View/AdminBoard/AdminAddBoard.html.twig
  src/View/AdminBoard/AdminEditBoard.html.twig
  src/View/Home/index.html.twig
  src/View/Section/section.html.twig
Labels: Reviewed, Corrections done

#305 fix value on edit
  .DS_Store
  public/.DS_Store
  src/.DS_Store
  src/View/AdminPartner/AdminEdit.html.twig
Labels: Reviewed

#314 deleted CGU, added links and fixed margin
  src/View/Components/_footer.html.twig
Labels: Reviewed

#315 fixed uppercase on membre
  src/View/Section/section.html.twig
Labels: Reviewed

#312 corrected upload path
  src/View/Section/section.html.twig
Labels: Reviewed

#316 fixed navbar burger admin
  src/View/Components/_admin_navbar.html.twig
Labels: Reviewed

#317 fix url on logo
  src/View/Partners/partner.html.twig
Labels: Reviewed

#313 fixed delete button partner
  src/View/AdminPartner/AdminPartner.html.twig
Labels: Reviewed

#311 color change on the hover dropdown for readabilty blue->white
  public/assets/css/navbar.css
Labels: Reviewed

#308 fixed all admins buttons
  src/View/AdminBoard/AdminAddBoard.html.twig
  src/View/AdminBoard/AdminBoard.html.twig
  src/View/AdminBoard/AdminEditBoard.html.twig
  src/View/AdminEvent/AddAdminEvent.html.twig
  src/View/AdminEvent/AdminEvent.html.twig
  src/View/AdminEvent/EditAdminEvent.html.twig
  src/View/AdminPartner/AdminEdit.html.twig
  src/View/AdminPartner/AdminPartner.html.twig
  src/View/AdminPartner/addPartner.html.twig
  src/View/AdminSports/adminSports.html.twig
  src/View/Components/_admin_form_add_sports.html.twig
  src/View/Components/_admin_form_edit_sports.html.twig
Labels: Reviewed

#319 fix errors txt on form and errorpage add polices on the form title
  public/assets/css/form.css
  src/Controller/AdminBoardController.php
  src/View/AdminBoard/AdminAddBoard.html.twig
  src/View/Contact/form.html.twig
  src/View/Error/Error.html.twig
Labels: Reviewed

#309 fix size card on gouvernance admin
  public/assets/css/style.css
  src/View/AdminBoard/AdminBoard.html.twig
Labels: Reviewed

#307 change btn et verif admin membre
  src/Controller/AdminBoardController.php
  src/View/AdminBoard/AdminAddBoard.html.twig
  src/View/AdminBoard/AdminBoard.html.twig
  src/View/AdminBoard/AdminEditBoard.html.twig
Labels: Reviewed, Corrections done

#310 changes circuit presentation image
  public/assets/css/circuit.css
  public/assets/images/circuit-presentation.jpeg
  src/View/Circuit/circuit.html.twig
Labels: Reviewed

#318 made new navigation from admin to visitor and adjusted error page and…
  public/assets/css/navbar_admin.css
  src/View/Components/_admin_navbar.html.twig
  src/View/Components/_footer.html.twig
  src/View/Error/Error.html.twig
  src/View/Partners/partner.html.twig
Labels: Reviewed

#320 fix du formulaire
  src/Controller/FormController.php
  src/View/Contact/form.html.twig
Labels: Reviewed

#324 fix size on logopart and change placeholder, link target, fix size ca…
  public/assets/css/partner.css
  public/assets/images/logoph.png
  public/assets/images/logopo.png
  src/View/AdminPartner/AdminEdit.html.twig
  src/View/AdminPartner/AdminPartner.html.twig
  src/View/AdminPartner/addPartner.html.twig
  src/View/Partners/partner.html.twig
Labels: Reviewed

#322 fix card
  src/Controller/EventAdminController.php
  src/View/AdminEvent/AdminEvent.html.twig
  src/View/AdminEvent/EditAdminEvent.html.twig
Labels: Reviewed

#306 remove padding admin event card
  src/View/AdminEvent/AdminEvent.html.twig
Labels: Reviewed

#328 fix text
  src/View/Home/index.html.twig
Labels: Reviewed

#327 ajout fin balise form
  src/View/AdminBoard/AdminBoard.html.twig
Labels: Reviewed

#325 new map with location marker
  src/View/Circuit/circuit.html.twig
Labels: Reviewed, Corrections done

#323 fix delete member
  src/Controller/AdminBoardController.php
  src/View/AdminBoard/AdminBoard.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#329 fix map location
  src/View/Circuit/circuit.html.twig
Labels: Reviewed

#331 dev -> main
  .DS_Store
  public/.DS_Store
  public/assets/css/card.css
  public/assets/css/circuit.css
  public/assets/css/form.css
  public/assets/css/navbar.css
  public/assets/css/navbar_admin.css
  public/assets/css/partner.css
  public/assets/css/section.css
  public/assets/css/style.css
  public/assets/images/circuit-presentation.jpeg
  public/assets/images/logoph.png
  public/assets/images/logopo.png
  src/.DS_Store
  src/Controller/AdminBoardController.php
  src/Controller/EventAdminController.php
  src/Controller/FormController.php
  src/Controller/HomeController.php
  src/View/AdminBoard/AdminAddBoard.html.twig
  src/View/AdminBoard/AdminBoard.html.twig
  src/View/AdminBoard/AdminEditBoard.html.twig
  src/View/AdminEvent/AddAdminEvent.html.twig
  src/View/AdminEvent/AdminEvent.html.twig
  src/View/AdminEvent/EditAdminEvent.html.twig
  src/View/AdminPartner/AdminEdit.html.twig
  src/View/AdminPartner/AdminPartner.html.twig
  src/View/AdminPartner/addPartner.html.twig
  src/View/AdminSports/adminSports.html.twig
  src/View/Circuit/circuit.html.twig
  src/View/Components/_admin_form_add_sports.html.twig
  src/View/Components/_admin_form_edit_sports.html.twig
  src/View/Components/_admin_navbar.html.twig
  src/View/Components/_footer.html.twig
  src/View/Contact/form.html.twig
  src/View/Error/Error.html.twig
  src/View/Home/index.html.twig
  src/View/Partners/partner.html.twig
  src/View/Section/section.html.twig
  src/routes.php
Labels: Reviewed, Dev -> Main

#330 made new relation between section and member
  database.sql
  src/Controller/AdminBoardController.php
  src/Controller/AdminSectionController.php
  src/Controller/SectionController.php
  src/Model/BoardManager.php
  src/Model/SectionManager.php
  src/View/AdminBoard/AdminAddBoard.html.twig
  src/View/AdminBoard/AdminEditBoard.html.twig
  src/View/Components/_admin_form_add_sports.html.twig
  src/View/Components/_admin_form_edit_sports.html.twig
  src/View/Section/section.html.twig
Labels: To be reviewed

#332 fixed memberadmin
  src/Controller/AdminBoardController.php
  src/View/AdminBoard/AdminAddBoard.html.twig
  src/View/AdminBoard/AdminEditBoard.html.twig
Labels: Reviewed

#333 dev -> main
  database.sql
  src/Controller/AdminBoardController.php
  src/Controller/AdminSectionController.php
  src/Controller/SectionController.php
  src/Model/BoardManager.php
  src/Model/SectionManager.php
  src/View/AdminBoard/AdminAddBoard.html.twig
  src/View/AdminBoard/AdminEditBoard.html.twig
  src/View/Components/_admin_form_add_sports.html.twig
  src/View/Components/_admin_form_edit_sports.html.twig
  src/View/Section/section.html.twig
Labels: Reviewed, Dev -> Main
