Repository WildCodeSchool/2022-09-php-orleans-project-ecurieorleans, pull requests merged in 2022-10, with the labels that each got.

#68 firstPR commit
  public/assets/css/root.css
  public/assets/fonts/Crossover-gxEwY.ttf
  public/assets/fonts/Roboto-Regular.ttf
  public/assets/fonts/Spiky016-axa75.otf
  src/View/layout.html.twig
Labels: Reviewed, Corrections done

#89 add page circuit and header for circuit
  public/assets/css/circuit.css
  public/assets/css/root.css
  public/assets/images/header_circuit2.jpeg
  src/Controller/CircuitController.php
  src/View/Circuit/circuit.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#76 HTML/CSS of a card Event
  composer.lock
  database.sql
  phpmd.xml
  public/assets/css/card.css
  public/assets/css/root.css
  public/assets/css/style.css
  public/assets/images/circuit2.jpeg
  src/Controller/HomeController.php
  src/Model/EventManager.php
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Corrections done

#94 S01US03 add card-image and fix title font
  database.sql
  public/assets/css/style.css
  public/assets/images/Card1.jpeg
Labels: Reviewed

#98 S01US03_change boostrap
  public/assets/css/card.css
  src/View/Home/index.html.twig
Labels: Reviewed

#99 First PR Dev -> Main
  composer.lock
  database.sql
  phpmd.xml
  public/assets/css/card.css
  public/assets/css/circuit.css
  public/assets/css/root.css
  public/assets/css/style.css
  public/assets/fonts/Crossover-gxEwY.ttf
  public/assets/fonts/Roboto-Regular.ttf
  public/assets/fonts/Spiky016-axa75.otf
  public/assets/images/Card1.jpeg
  public/assets/images/header_circuit2.jpeg
  src/Controller/CircuitController.php
  src/Controller/HomeController.php
  src/Model/EventManager.php
  src/View/Circuit/circuit.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed, Dev -> Main

#97 S01 us41 homepage header
  public/assets/css/home.css
  public/assets/css/root.css
  public/assets/css/style.css
  public/assets/images/arrow-down.svg
  public/assets/images/home_cover.jpg
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Conflicts resolve

#92 First version of navbar
  public/assets/css/navbar.css
  public/assets/images/FLAGDRAP.jpeg
  public/assets/images/NavLogo.png
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Corrections done, Conflicts resolve

#91 S1 us09 paragraph presentation association
  database.sql
  public/assets/css/presentation.css
  public/assets/css/root.css
  public/assets/css/style.css
  src/Manette/HomeController.php
  src/Model/AssociationManager.php
  src/View/Home/index.html.twig
Labels: Reviewed, Corrections done

#101 PR#2 - Dev->main
  database.sql
  public/assets/css/home.css
  public/assets/css/navbar.css
  public/assets/css/presentation.css
  public/assets/css/root.css
  public/assets/css/style.css
  public/assets/images/FLAGDRAP.jpeg
  public/assets/images/NavLogo.png
  public/assets/images/arrow-down.svg
  public/assets/images/home_cover.jpg
  src/Manette/HomeController.php
  src/Model/AssociationManager.php
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Dev -> Main

#103 fix dev
  database.sql
  public/assets/css/style.css
  src/Controller/HomeController.php
Labels: Reviewed, Corrections done

#104 PR #3 Dev -> Main
  database.sql
  public/assets/css/style.css
  src/Controller/HomeController.php
Labels: Reviewed, Dev -> Main

#105 S02 us04 circuit presentation
  public/assets/css/card.css
  public/assets/css/circuit.css
  public/assets/css/root.css
  public/assets/css/style.css
  public/assets/images/circuit.webp
  public/assets/images/circuit_description.webp
  public/assets/images/circuit_presentation.jpeg
  public/assets/images/logo.png
  src/View/Circuit/circuit.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed
